### PR TITLE
Fix sortable_serialise API wrapping

### LINKED ISSUE #54: xapian_sortable_serialise() wrapping flawed
The `std::string` returned by `Xapian::sortable_serialise()` is essentially a binary blob, and may contain embedded zero bytes.  But the current wrappers document the serialised form as `(array zero-terminated=1)` and handle the data assuming the first zero byte marks the end of the string.

Because of how the serialisation inherently works, this generally results in rounding-off type errors, rather than completely the wrong answer being returned.  For example, if you roundtrip `2049.0` through the serialisation as wrapped by xapian-glib, you get `2048.0` back out.

However for numbers which produce a serialisation starting with a zero byte, the truncation means you'll get -infinity back.  Not sure exactly which values trigger this, but they must be negative.

To fix this, I think the length needs to be returned and passed back in, something like:

```
char *
xapian_sortable_serialise (double value, size_t *len)
{
  char *buf;
  const string &result = Xapian::sortable_serialise (value);
  *len = result.size();
  buf = g_malloc (*len);
  memcpy (buf, result.data (), *len);
  return buf;
}

double
xapian_sortable_unserialise (const char *value, size_t len)
{
  return Xapian::sortable_unserialise (string (value, len));
}
```

But that's clearly an incompatible change, so I'm not sure how best to address this.

I noticed looking at the git history that `xapian_document_add_numeric_value ()` was added because these wrappers aren't usable from Gjs (because they don't return UTF-8 strings), so perhaps they aren't actually used by anyone currently (which would explain why nobody's noticed this issue - I spotted it while looking at the code).

### PR DESCRIPTION
**Pull request by ojwb**
The returned strings can contain zero bytes, so we need to return
and accept a length as well as the string data.

Fixes #54.

### CODE REVIEW

File: xapian-glib/xapian-utils.cc [hunk 1]
```diff
@@ -135,28 +137,40 @@ xapian_revision (void)
...
  *
- * Returns: (transfer full) (array zero-terminated=1) (element-type guint8): the serialised value
+ * Returns: (transfer full) (array length=len): the serialised value
  *
  * Since: 1.4
  */
-char *
-xapian_sortable_serialise (double value)
+guchar *
+xapian_sortable_serialise (double value, gsize *len)
```
Comment (ebassi) [inline xapian-glib/xapian-utils.cc]: Coding style: arguments after the first go on a new line, aligned with the first argument.

File: xapian-glib/xapian-utils.cc [hunk 2]
```diff
@@ -135,28 +137,40 @@ xapian_revision (void)
...
 {
-  return g_strdup (Xapian::sortable_serialise (value).c_str ());
+  const std::string &result = Xapian::sortable_serialise (value);
+  gsize size = result.size ();
+  guchar *buf = static_cast<guchar *> (g_malloc (size));
+
+  *len = size;
```
Comment (ebassi) [inline xapian-glib/xapian-utils.cc]: There should be a precondition check on the out `len` argument, like:

```cpp
  g_return_val_if_fail (len != NULL, NULL);
```

Since it's a programmer error to pass a `NULL` there.

File: xapian-glib/xapian-utils.cc [hunk 3]
```diff
@@ -167,7 +181,8 @@ xapian_sortable_serialise (double value)
  * Since: 1.4
  */
 double
-xapian_sortable_unserialise (const char *value)
+xapian_sortable_unserialise (const guchar *value, gsize len)
```
Comment (ebassi) [inline xapian-glib/xapian-utils.cc]: Coding style: arguments after the first go on a new line, aligned with the first argument.

File: xapian-glib/xapian-utils.h [hunk 4]
```diff
@@ -39,9 +39,9 @@ int             xapian_minor_version            (void);
 XAPIAN_GLIB_AVAILABLE_IN_1_0
 int             xapian_revision                 (void);
 XAPIAN_GLIB_AVAILABLE_IN_1_4
-char *          xapian_sortable_serialise       (double value);
+guchar *        xapian_sortable_serialise       (double value, gsize *len);
```
Comment (ebassi) [inline xapian-glib/xapian-utils.h]: Coding style: arguments after the first go on a new line, aligned with the first argument.

File: xapian-glib/xapian-utils.h [hunk 5]
```diff
@@ -39,9 +39,9 @@ int             xapian_minor_version            (void);
...
 XAPIAN_GLIB_AVAILABLE_IN_1_4
-double          xapian_sortable_unserialise     (const char *value);
+double          xapian_sortable_unserialise     (const guchar *value, gsize len);
```
Comment (ebassi) [inline xapian-glib/xapian-utils.h]: Coding style: arguments after the first go on a new line, aligned with the first argument.

File: xapian-glib/xapian-utils.cc (hunk 1 above)
Comment (ojwb) [inline xapian-glib/xapian-utils.cc]: OK, though that's not adhered to rigorously currently - I'll send a patch to fix those too.

File: xapian-glib/xapian-utils.cc (hunk 2 above)
Comment (ojwb) [inline xapian-glib/xapian-utils.cc]: I've added one for the `value` pointer in the other function too.

File: xapian-glib/xapian-utils.cc (hunk 1 above)
Comment (ojwb) [inline xapian-glib/xapian-utils.cc]: That patch is #58.

**Comment by ojwb** [comment]
Indeed, should be good to go.  I can squash into one commit if you prefer.

**Comment by ebassi** [comment]
@ojwb That's fine.
